// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntwmdcznhsssyqpjuemg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50d21kY3puaHNzc3lxcGp1ZW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMDMxNzUsImV4cCI6MjA1NjU3OTE3NX0.A53XsGUaOQQn0C_wzwN34UGn_fXDHKbDATTe1NGkAI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);